apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend-service.fullname" . }}-secrets
  labels:
    {{- include "frontend-service.labels" . | nindent 4 }}
type: Opaque
data:
  ui-client-secret: {{ .Values.secrets.uiClientSecret | b64enc | quote }}
