replicaCount: 1

image:
  repository: accounts-service
  tag: 0.0.3-SNAPSHOT
  pullPolicy: IfNotPresent

fullnameOverride: accounts-service

service:
  port: 9092

secrets:
  serviceClientSecret: jqfP3f78QoeJ3VYNKm17CBSDKu212Int

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
