apiVersion: v2
name: bank
description: Umbrella Helm chart for my-bank-app. Combines PostgreSQL (StatefulSet) and backend microservices as subcharts.
type: application
version: 0.1.0
appVersion: 0.0.3-SNAPSHOT

dependencies:
  - name: postgres
    version: 0.1.0
    repository: file://../postgres
    condition: postgres.enabled
  - name: kafka
    version: 0.1.0
    repository: file://../kafka
    condition: kafka.enabled
  - name: accounts-service
    version: 0.1.0
    repository: file://../accounts-service
    condition: accounts-service.enabled
  - name: cash-service
    version: 0.1.0
    repository: file://../cash-service
    condition: cash-service.enabled
  - name: transfer-service
    version: 0.1.0
    repository: file://../transfer-service
    condition: transfer-service.enabled
  - name: notification-service
    version: 0.1.0
    repository: file://../notification-service
    condition: notification-service.enabled
  - name: keycloak
    version: 0.1.0
    repository: file://../keycloak
    condition: keycloak.enabled
