replicaCount: 1

image:
  repository: cash-service
  tag: 0.0.3-SNAPSHOT
  pullPolicy: IfNotPresent

fullnameOverride: cash-service

service:
  port: 8084

secrets:
  serviceClientSecret: ed665a3b915cd26c6652a07ae684d513

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

kafka:
  bootstrapServers: "bank-kafka-broker:9092"
