apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://keycloak:8080/realms/bank-realm
      cloud:
        gateway:
          server:
            webflux:
              routes:
                - id: accounts-service
                  uri: http://accounts-service:9092
                  predicates:
                    - Path=/api/accounts/**
                  filters:
                    - name: RequestLogging
                    - name: JwtTokenRelay
                - id: transfer-service
                  uri: http://transfer-service:8083
                  predicates:
                    - Path=/api/transfers/**
                  filters:
                    - name: RequestLogging
                    - name: JwtTokenRelay
                - id: cash-service
                  uri: http://cash-service:8084
                  predicates:
                    - Path=/api/cash/**
                  filters:
                    - name: RequestLogging
                    - name: JwtTokenRelay
    server:
      port: 9091
    logging:
      level:
        ru.yandex.practicum.gateway: DEBUG
        org.springframework.cloud.gateway: TRACE
