apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transfer-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transfer-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "optional:file:/config/"
            - name: SERVICE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "transfer-service.fullname" . }}-secrets
                  key: service-client-secret
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "transfer-service.fullname" . }}-config
