replicaCount: 1

image:
  repository: frontend-service
  tag: 0.0.3-SNAPSHOT
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: frontend-service

service:
  type: ClusterIP
  port: 9090

secrets:
  uiClientSecret: ui-client-secret

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
