replicaCount: 1

image:
  repository: notification-service
  tag: 0.0.3-SNAPSHOT
  pullPolicy: IfNotPresent

fullnameOverride: notification-service

service:
  port: 8085

probes:
  path: /actuator/health

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
