apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk.kibana.fullname" . }}-config
  labels:
    {{- include "elk.kibana.labels" . | nindent 4 }}
data:
  kibana.yml: |
    {{- .Values.kibana.config | nindent 4 }}