apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk.logstash.fullname" . }}-config
  labels:
    {{- include "elk.logstash.labels" . | nindent 4 }}
data:
  logstash.yml: |
    {{- .Values.logstash.config | nindent 4 }}
  pipelines.yml: |
    {{- .Values.logstash.pipelines | nindent 4 }}
  bank-logs.conf: |
    {{- .Values.logstash.pipelineConfig | nindent 4 }}