spring:
  application:
    name: accounts-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

app:
  outbox:
    poll-interval: 5000
    batch-size: 100

clients:
  notification-service:
    url: http://notification-service:8085
