spring:
  application:
    name: accounts-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

clients:
  notification-service:
    url: http://notification-service:8085
