plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation libs.spring.cloud.starter.gateway
    implementation libs.spring.cloud.gateway.server.webflux
    implementation libs.spring.boot.starter.oauth2.client
    implementation libs.spring.boot.starter.oauth2.resource.server
    implementation libs.spring.boot.starter.actuator
    implementation libs.micrometer.tracing.bridge.brave
    implementation libs.zipkin.reporter.brave
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testImplementation libs.spring.boot.starter.test
}
