apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-service.fullname" . }}-secrets
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
type: Opaque
data:
  service-client-secret: {{ .Values.secrets.serviceClientSecret | b64enc | quote }}
